language: erlang
notifications:
  recipients:
    - thiagown@gmail.com
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.get
script:
  - mix test
services:
  - memcached
