language: erlang
notifications:
  recipients:
    - thiagown@gmail.com
otp_release:
  - 17.0
before_install:
  - sudo apt-get -y -qq --purge remove memcached
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
  - sudo apt-get update
  - sudo apt-get install memcached_1.4.13
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.get
script:
  - mix test
